version: '3.8'

services:
  frontend:
    image: ghcr.io/drap-3312/vue-test-deploy:latest
    
    networks:
      - caddy
    environment:
      - PORT=80
    deploy:
      replicas: 1
      labels:
        caddy: "saguarodrap.dev"
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls: "davidake117@gmail.com"

networks:
  caddy:
    external: true